version: '2'

services:
  drone:
    image: drone/drone:0.8.0
    ports:
      - 8085:8000
    networks:
      - front
      - back
    #env_file: ./drone/dronerc
    environment:
     #REMOTE_DRIVER=gogs
     #REMOTE_CONFIG=http://192.168.33.15:9080/?open=false
     - DRONE_DATABASE_DRIVER=postgres
     - DRONE_DATABASE_DATASOURCE=postgres://root:admin@192.168.33.15:5432/gogs?sslmode=disable
     #postgres://root:password@1.2.3.4:5432/postgres?sslmode=disable
     - DRONE_HOST=${DRONE_HOST}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=root    
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gogs 
    ports:
      - 5432:5432
    networks:
      - back
  gogs:
    image: gogs/gogs:0.11.29
    #image: gogs/gogs:0.9.141
    #image: gogs/gogs:0.9.13
    ports:
      - "9022:1302"
      - "9080:3000"
    networks:
      - front
      - back
    volumes:
      - ./gogs:/data

networks:
  front:
    driver: bridge
  back:
    driver: bridge
