#!/bin/sh
set -e

. ~/.local/etc/github.sh
. ~/.local/etc/bitbucket.sh

{ cat <<EOM
DRONE_HOST=http://sandbox-3:8080
DRONE_GITHUB_CLIENT=$GH_BOREAS_DRONE_ID
DRONE_GITHUB_SECRET=$GH_BOREAS_DRONE_SECRET
DRONE_BITBUCKET_CLIENT=$GH_BOREAS_DRONE_ID
DRONE_BITBUCKET_SECRET=$GH_BOREAS_DRONE_SECRET
DRONE_SECRET=r29qqqJVFQuyk3eguQ
EOM
} > .env
